### ISSUE TITLE
 Module 'has no exported member 'VisibilityProperty'.

### ISSUE THREAD

**Issue by radu-marinescu-rm** [shivasiddharth/DIY-Echo-Show#10]
[./main.css] 1.05 KiB {main} [built]
[./main.tsx] 568 bytes {main} [built]
    + 33 hidden modules

ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/APLRendererWindow.tsx
./components/APLRendererWindow.tsx
[tsl] ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/APLRendererWindow.tsx(23,10)
      TS2305: Module '"/home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/node_modules/csstype/index"' has no exported member 'VisibilityProperty'.

ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/VoiceChrome.tsx
./components/VoiceChrome.tsx
[tsl] ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/VoiceChrome.tsx(7,10)
      TS2305: Module '"/home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/node_modules/csstype/index"' has no exported member 'VisibilityProperty'.
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
       4 modules
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! gui@1.0.0 build: `npm run lint && webpack --config webpack.config.js "--output-path" "/home/pi/DIY-Echo-Show/Alexa/ss-build/modules/GUI" "--define" "DISABLE_WEBSOCKET_SSL=true"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the gui@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-14T16_41_44_803Z-debug.log
make[2]: *** [modules/GUI/CMakeFiles/GUIClient.dir/build.make:59: modules/GUI/CMakeFiles/GUIClient] Error 2
make[1]: *** [CMakeFiles/Makefile2:2152: modules/GUI/CMakeFiles/GUIClient.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by shivasiddharth** [comment]
You already have a related issue open. Closing this one.
