### ISSUE TITLE
alexavoiceinstaller.sh freezing up

### ISSUE THREAD

**Issue by shawnpaffhausen** [shivasiddharth/DIY-Echo-Show#2]
when i run the alexavoiceinstaller.sh it constantly freezes at

95% Building CXX object SampleApp/src/CMakeFiles/LibSampleApp.dir/InteractionManager.cpp.o

restarted and rerun brings the same issue

**Comment by shivasiddharth** [comment]
Which board are you using ? Did you increase the swap partition size or the swap file size ? https://www.youtube.com/watch?v=u_0Y40yO2VU

**Comment by shawnpaffhausen** [comment]
Raspberry pi3b + I'll try that..Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: shivasiddharth <notifications@github.com> Date: 7/30/20  21:59  (GMT-05:00) To: shivasiddharth/DIY-Echo-Show <DIY-Echo-Show@noreply.github.com> Cc: shawnpaffhausen <shawnpaffhausen@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [shivasiddharth/DIY-Echo-Show] alexavoiceinstaller.sh freezing up (#2) 
Which board are you using ? Did you increase the swap partition size or the swap file size ? https://www.youtube.com/watch?v=u_0Y40yO2VU

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/shivasiddharth/DIY-Echo-Show/issues/2#issuecomment-666869605",
"url": "https://github.com/shivasiddharth/DIY-Echo-Show/issues/2#issuecomment-666869605",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by shawnpaffhausen** [comment]
Switched it to 1024 and stop the stall thanks
