### ISSUE TITLE
error during prep

### ISSUE THREAD

**Issue by shawnpaffhausen** [shivasiddharth/DIY-Echo-Show#4]
pi@raspberrypi:~ $ systemctl status seeed-voicecard.service
● seeed-voicecard.service - Seeed Voicecard service
   Loaded: loaded (/lib/systemd/system/seeed-voicecard.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-08-02 22:28:49 EDT; 54s ago
  Process: 8549 ExecStart=/usr/bin/seeed-voicecard (code=exited, status=1/FAILURE)
 Main PID: 8549 (code=exited, status=1/FAILURE)

Aug 02 22:28:48 raspberrypi su[8658]: pam_unix(su:session): session closed for user pi
Aug 02 22:28:48 raspberrypi su[8688]: (to pi) root on none
Aug 02 22:28:48 raspberrypi su[8688]: pam_unix(su:session): session opened for user pi by (uid=0)
Aug 02 22:28:48 raspberrypi su[8688]: pam_unix(su:session): session closed for user pi
Aug 02 22:28:49 raspberrypi sudo[8699]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/cp /etc/asound.conf /h
Aug 02 22:28:49 raspberrypi sudo[8699]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 02 22:28:49 raspberrypi sudo[8699]: pam_unix(sudo:session): session closed for user root
Aug 02 22:28:49 raspberrypi systemd[1]: seeed-voicecard.service: Main process exited, code=exited, status=1/FAILURE
Aug 02 22:28:49 raspberrypi systemd[1]: seeed-voicecard.service: Failed with result 'exit-code'.
Aug 02 22:28:49 raspberrypi systemd[1]: Failed to start Seeed Voicecard service.

**Comment by shawnpaffhausen** [comment]
which version of raspbian was this geared to

**Comment by shivasiddharth** [comment]
This works with the latest version of Buster. It would be great if you could provide more details than just copy pasting parts of issues.
