### ISSUE TITLE
Failed to create sample application

### ISSUE THREAD

**Issue by radu-marinescu-rm** [shivasiddharth/DIY-Echo-Show#8]
#################################################
#       NOTIFICATION INDICATOR STATE: OFF       #
#################################################

##################################
#       NOT YET AUTHORIZED       #
##################################

################################################################################################
#       To authorize, browse to: 'https://amazon.com/us/code' and enter the code: C6BYXW       #
################################################################################################

#################################################
#       Checking for authorization (1)...       #
#################################################

Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2043
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2714
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2838
2021-02-13 12:02:22.887 [  1] C PortAudioMicrophoneWrapper:Failed to open PortAudio default stream:errorCode=-9997
2021-02-13 12:02:22.887 [  1] C PortAudioMicrophoneWrapper:Failed to initialize PortAudioMicrophoneWrapper
2021-02-13 12:02:22.897 [  1] C SampleApplication:Failed to create microphone wrapper!
2021-02-13 12:02:22.912 [  5] E FocusManager:releaseChannelHelper:reason=releaseActivityFailed,channel=0x1e1d448,interface=
2021-02-13 12:02:22.931 [  1] C SampleApplication:Failed to initialize SampleApplication
Failed to create SampleApplication!

**Comment by shivasiddharth** [comment]
You need to authenticate first.

**Comment by radu-marinescu-rm** [comment]
i authenticate successful but this error will fail the final execution?
SampleApplication:Failed to create microphone wrapper!

**Comment by shivasiddharth** [comment]
Another active issue present. Closing this.
